version: "2"

services:
  engine:
    image: qlikcore/engine:12.387.0
    command: -S AcceptEULA=${ACCEPT_EULA} -S DocumentDirectory=/docs
    ports:
      - "19076:9076"
    volumes: 
      - ./documents:/docs
